### ISSUE TITLE
unable to start the program

### ISSUE THREAD

**Issue by shadowelite-sec** [0bCdian/Waypaper-Engine#13]
getting this error when i try to run

```bash
 waypaper-engine run
TypeError: Cannot open database because the directory does not exist
    at new Database (/opt/waypaper-engine/resources/app/node_modules/better-sqlite3/lib/database.js:65:9)
    at Database (/opt/waypaper-engine/resources/app/node_modules/better-sqlite3/lib/database.js:11:10)
    at go (/opt/waypaper-engine/resources/app/dist-electron/main.js:38:18096)
    at Xu (/opt/waypaper-engine/resources/app/dist-electron/main.js:38:18279)
    at Object.<anonymous> (/opt/waypaper-engine/resources/app/dist-electron/main.js:38:18339)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
Error: Could not create better-sqlite3 connector electron /opt/waypaper-engine/resources/app/dist-electron dirname
    at go (/opt/waypaper-engine/resources/app/dist-electron/main.js:38:18167)
    at Xu (/opt/waypaper-engine/resources/app/dist-electron/main.js:38:18279)
    at Object.<anonymous> (/opt/waypaper-engine/resources/app/dist-electron/main.js:38:18339)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at node:electron/js2c/browser_init:2:121151
    at node:electron/js2c/browser_init:2:121360
TypeError: Cannot open database because the directory does not exist
    at new Database (/opt/waypaper-engine/resources/app/node_modules/better-sqlite3/lib/database.js:65:9)
    at Database (/opt/waypaper-engine/resources/app/node_modules/better-sqlite3/lib/database.js:11:10)
    at go (/opt/waypaper-engine/resources/app/dist-electron/main.js:38:18096)
    at new Ju (/opt/waypaper-engine/resources/app/dist-electron/main.js:38:20109)
    at Object.<anonymous> (/opt/waypaper-engine/resources/app/dist-electron/main.js:38:24814)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Could not create better-sqlite3 connector electron /opt/waypaper-engine/resources/app/dist-electron dirname
    at go (/opt/waypaper-engine/resources/app/dist-electron/main.js:38:18167)
    at new Ju (/opt/waypaper-engine/resources/app/dist-electron/main.js:38:20109)
    at Object.<anonymous> (/opt/waypaper-engine/resources/app/dist-electron/main.js:38:24814)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1311:10)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at node:electron/js2c/browser_init:2:121151
    at node:electron/js2c/browser_init:2:121360

(waypaper-engine-bin:1366): Gtk-WARNING **: 20:25:39.793: Theme parsing error: gtk.css:407:20: '' is not a valid color name
[1366:0507/202539.886208:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[1366:0507/202539.886242:ERROR:select_file_dialog_linux_portal.cc(286)] Failed to read portal version property
libva error: /usr/lib/dri/nvidia_drv_video.so init failed
```

**Comment by 0bCdian** [comment]
I was able to replicate this, it was an oversight from my part when migrating to a different orm, I'll try to fix this by this afternoon. Sorry for the inconvenience

**Comment by 0bCdian** [comment]
Already fixed this issue on latest git, pull the latest changes if you installed manually, or install via aur (already pushed the latest fix release) and test it out, let me know if anything else pops up!

**Comment by shadowelite-sec** [comment]
> Already fixed this issue on latest git, pull the latest changes if you installed manually, or install via aur (already pushed the latest fix release) and test it out, let me know if anything else pops up!

yes the git version is working now ,
Thanks a lot! I just wanted to say, I really enjoyed this project.
