### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by Heyian** [0bCdian/Waypaper-Engine#23]
Hi, I can't build either the waypaper-engine or the waypaper-engine-git.

It builds fine when I do it manually though. (git clone...)

The problem seems to be that the folder .../.cache/paru/clone/waypaper-engine/src/Waypaper-Engine-2.0.3/node_modules/app-builder-lib/src does not exists. 

.../.cache/paru/clone/waypaper-engine/src/Waypaper-Engine-2.0.3/node_modules/app-builder-lib/ contains :
certs, node_modules, out, templates, package.json and scheme.json. There's no src folder.

Here's the tail of the build :
```
vite v4.5.3 building for production...
✓ 229 modules transformed.
dist-electron/preload.js  193.79 kB │ gzip: 63.81 kB
✓ built in 437ms
  • electron-builder  version=24.13.3 os=6.9.5-zen1-1-zen
  • loaded configuration  file=/home/mafavreau/.cache/paru/clone/waypaper-engine/src/Waypaper-Engine-2.0.3/electron-builder.json
  • description is missed in the package.json  appPackageFile=/home/mafavreau/.cache/paru/clone/waypaper-engine/src/Waypaper-Engine-2.0.3/package.json
  • @electron/rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=release/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=better-sqlite3@9.5.0 platform=linux arch=x64
  • install prebuilt binary  name=better-sqlite3 version=9.5.0 platform=linux arch=x64 napi=
  • packaging       platform=linux arch=x64 electron=29.3.0 appOutDir=release/linux-unpacked
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
  • Cannot detect repository by .git/config. Please specify "repository" in the package.json (https://docs.npmjs.com/files/package.json#repository).
Please see https://electron.build/configuration/publish
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
  • building        target=AppImage arch=x64 file=release/waypaper-engine.AppImage
  • Cannot detect repository by .git/config. Please specify "repository" in the package.json (https://docs.npmjs.com/files/package.json#repository).
Please see https://electron.build/configuration/publish
  • Cannot detect repository by .git/config. Please specify "repository" in the package.json (https://docs.npmjs.com/files/package.json#repository).
Please see https://electron.build/configuration/publish
  ⨯ Cannot read properties of null (reading 'channel')  failedTask=build stackTrace=TypeError: Cannot read properties of null (reading 'channel')
    at computeChannelNames (/home/mafavreau/.cache/paru/clone/waypaper-engine/src/Waypaper-Engine-2.0.3/node_modules/app-builder-lib/src/publish/updateInfoBuilder.ts:47:74)
    at createUpdateInfoTasks (/home/mafavreau/.cache/paru/clone/waypaper-engine/src/Waypaper-Engine-2.0.3/node_modules/app-builder-lib/src/publish/updateInfoBuilder.ts:143:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'waypaper-engine-2.0.3-1': 
error: packages failed to build: waypaper-engine-2.0.3-1
```

**Comment by 0bCdian** [comment]
I tried with yay and had not problems. Try deleting the cache or clean building? If it's builds in local I don't think that's an issue on my part, rather with the package manager you're using. I'm using yay, I just did a yay -Rns waypaper-engine-git and reinstalled without using the cache and worked without hiccups. Try it like that to see if it works, this looks like package manager shenanigans tbh.

**Comment by Heyian** [comment]
I really can't figure out what's going on. Even if I manually build from the yay's cache folder, I still got the same error. I can't put more time on this, I got to work ;) I'll close the issue since you think the problem is on my side, I just can't figure out what's broken. Good day!

**Comment by Heyian** [comment]
Hi, I had alerts for any PR or releases and I just wanted to let you know that it now builds without any issue on the git package. I'm pretty I haven't changed anything on my side and I have no idea if anything you did fixed this but now I can build it with Yay instead of manually building it from the repo.
Have a good day!
